'use strict';

var creatures = {
    umber_couch: {
        name: 'Umber Couch',
        health: 200,
        damage: 4,
        hitson: 60,
        cooldown: 30,
        range: 105,
        attackText: "butts its upholstery against you",
        speed: 50,
    },
    hand_flayer: {
        name: 'Hand Flayer',
        health: 25,
        damage: 6,
        hitson: 80,
        cooldown: 60,
        range: 70,
        attackText: 'slaps you with its slimy hand-tentacles',
        speed: 100,
    },
    bearicorn: {
        name: 'Bearicorn',
        health: 150,
        damage: 8,
        hitson: 65,
        cooldown: 60,
        range: 70,
        attackText: 'gores you with its sparkly horn',
        speed: 95,
    },
    ochre_cube: {
        name: 'Ochre Cube',
        health: 50,
        damage: 1,
        hitson: 90,
        cooldown: 0,
        range: -35,
        attackText: 'leaves permanent turmeric stains on your clothing',
        speed: 25,
    },
    owlpig: {
        name: 'Owlpig',
        health: 100,
        damage: 6,
        hitson: 50,
        cooldown: 60,
        range: 70,
        attackText: 'pecks visciously at you with its snout',
        speed: 110,
    },
    globlin: {
        name: 'Globlin',
        health: 10,
        damage: 2,
        hitson: 80,
        cooldown: 120,
        range: 250,
        attackText: 'throws a globule of itself at you',
        speed: 125,
    }
}
